#!/bin/bash
#============================================================
# cloud_sign.sh
# ─ AIPMシステム用 クラウドサイン（電子署名・承認）ツール
#
# 使い方:
#   ./cloud_sign.sh sign   <file> [--signer <name>]
#   ./cloud_sign.sh verify <file>
#   ./cloud_sign.sh status <file>
#   ./cloud_sign.sh list   [directory]
#   ./cloud_sign.sh approve <file> [--signer <name>]
#   ./cloud_sign.sh revoke <file> [--signer <name>]
#   ./cloud_sign.sh log    [--limit <n>]
#
# 概要:
#   Flow/Stock ワークフローと連携し、ドキュメントへの
#   電子署名・承認・検証を行うツールです。
#   署名記録は .signatures/ ディレクトリに YAML 形式で保存されます。
#============================================================

set -e

# ─── 色定義 ───
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# ─── ログ関数 ───
log_info()    { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error()   { echo -e "${RED}[ERROR]${NC} $1"; }

# ─── 定数 ───
SIGNATURES_DIR=".signatures"
SIGN_LOG_FILE="${SIGNATURES_DIR}/sign_log.txt"
VERSION="1.0.0"

# ─── ワークスペースルートの検出 ───
find_workspace_root() {
  local dir="$PWD"
  while [ "$dir" != "/" ]; do
    if [ -d "$dir/Flow" ] && [ -d "$dir/Stock" ]; then
      echo "$dir"
      return 0
    fi
    # .git があればそこをルートとする（Flow/Stockがまだ無い場合）
    if [ -d "$dir/.git" ]; then
      echo "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  echo "$PWD"
}

WORKSPACE_ROOT="$(find_workspace_root)"

# ─── 署名ディレクトリの初期化 ───
init_signatures_dir() {
  local sig_dir="${WORKSPACE_ROOT}/${SIGNATURES_DIR}"
  if [ ! -d "$sig_dir" ]; then
    mkdir -p "$sig_dir"
    log_info "署名ディレクトリを作成しました: ${sig_dir}"
  fi
}

# ─── 署名者名の取得 ───
get_signer_name() {
  local signer="$1"
  if [ -z "$signer" ]; then
    # git config から取得を試みる
    signer=$(git config user.name 2>/dev/null || true)
  fi
  if [ -z "$signer" ]; then
    signer="${USER:-unknown}"
  fi
  echo "$signer"
}

# ─── ファイルのSHA256ハッシュ計算 ───
compute_hash() {
  local file="$1"
  if command -v sha256sum > /dev/null 2>&1; then
    sha256sum "$file" | awk '{print $1}'
  elif command -v shasum > /dev/null 2>&1; then
    shasum -a 256 "$file" | awk '{print $1}'
  else
    log_error "sha256sum または shasum が見つかりません"
    exit 1
  fi
}

# ─── 署名ファイルパスの生成 ───
get_sig_file_path() {
  local file="$1"
  local abs_path
  abs_path="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
  local rel_path="${abs_path#${WORKSPACE_ROOT}/}"
  # パス区切り文字を _ に変換してフラットなファイル名にする
  local sig_name
  sig_name=$(echo "$rel_path" | sed 's/\//__/g')
  echo "${WORKSPACE_ROOT}/${SIGNATURES_DIR}/${sig_name}.sig.yaml"
}

# ─── 現在時刻の取得 (ISO 8601) ───
get_timestamp() {
  date +"%Y-%m-%dT%H:%M:%S%z" 2>/dev/null || date +"%Y-%m-%dT%H:%M:%S"
}

# ─── 署名ログの追記 ───
append_sign_log() {
  local action="$1"
  local file="$2"
  local signer="$3"
  local timestamp="$4"
  local hash="$5"
  echo "${timestamp} | ${action} | ${signer} | ${file} | ${hash}" >> "${WORKSPACE_ROOT}/${SIGN_LOG_FILE}"
}

# ================================================================
# サブコマンド: sign
# ドキュメントに電子署名する
# ================================================================
cmd_sign() {
  local file=""
  local signer=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --signer) signer="$2"; shift 2 ;;
      *) file="$1"; shift ;;
    esac
  done

  if [ -z "$file" ]; then
    log_error "署名するファイルを指定してください"
    echo "使い方: $0 sign <file> [--signer <name>]"
    exit 1
  fi

  if [ ! -f "$file" ]; then
    log_error "ファイルが見つかりません: $file"
    exit 1
  fi

  signer="$(get_signer_name "$signer")"
  init_signatures_dir

  local abs_path
  abs_path="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
  local rel_path="${abs_path#${WORKSPACE_ROOT}/}"
  local hash
  hash="$(compute_hash "$file")"
  local timestamp
  timestamp="$(get_timestamp)"
  local sig_file
  sig_file="$(get_sig_file_path "$file")"

  # 既存の署名ファイルがあるか確認
  if [ -f "$sig_file" ]; then
    # 既に同じ署名者の署名があるか確認
    if grep -q "name: \"${signer}\"" "$sig_file" 2>/dev/null; then
      log_warning "「${signer}」は既にこのドキュメントに署名しています"
      echo ""
      echo -e "${YELLOW}再署名しますか？ ドキュメントが更新された場合はハッシュが更新されます。${NC}"
      echo -n "[y/N]: "
      read -r confirm
      if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        log_info "署名をキャンセルしました"
        return 0
      fi
      # 既存の署名者エントリを更新（簡易実装: ファイル全体を再生成）
    fi

    # 署名者を追加（既存ファイルに追記）
    cat >> "$sig_file" << SIGENTRY
  - name: "${signer}"
    signed_at: "${timestamp}"
    sha256: "${hash}"
    status: "signed"
SIGENTRY
  else
    # 新規署名ファイルの作成
    cat > "$sig_file" << SIGFILE
# Cloud Sign - 電子署名記録
# Generated by cloud_sign.sh v${VERSION}
---
document:
  path: "${rel_path}"
  filename: "$(basename "$file")"
  signed_first_at: "${timestamp}"
  current_sha256: "${hash}"

signatures:
  - name: "${signer}"
    signed_at: "${timestamp}"
    sha256: "${hash}"
    status: "signed"

approval:
  status: "pending"
  required_signers: []
  approved_at: ""
SIGFILE
  fi

  append_sign_log "SIGN" "$rel_path" "$signer" "$timestamp" "$hash"

  echo ""
  echo -e "${GREEN}${BOLD}=== 署名完了 ===${NC}"
  echo -e "  ファイル:   ${CYAN}${rel_path}${NC}"
  echo -e "  署名者:     ${BOLD}${signer}${NC}"
  echo -e "  日時:       ${timestamp}"
  echo -e "  SHA256:     ${hash:0:16}..."
  echo -e "  署名記録:   ${SIGNATURES_DIR}/$(basename "$sig_file")"
  echo ""
  log_success "ドキュメントへの署名が完了しました"
}

# ================================================================
# サブコマンド: verify
# ドキュメントの署名を検証する
# ================================================================
cmd_verify() {
  local file="$1"

  if [ -z "$file" ]; then
    log_error "検証するファイルを指定してください"
    echo "使い方: $0 verify <file>"
    exit 1
  fi

  if [ ! -f "$file" ]; then
    log_error "ファイルが見つかりません: $file"
    exit 1
  fi

  local sig_file
  sig_file="$(get_sig_file_path "$file")"

  if [ ! -f "$sig_file" ]; then
    log_error "署名記録が見つかりません: このドキュメントは署名されていません"
    exit 1
  fi

  local current_hash
  current_hash="$(compute_hash "$file")"

  # 署名ファイルから記録されたハッシュを取得
  local recorded_hash
  recorded_hash=$(grep "current_sha256:" "$sig_file" | head -1 | sed 's/.*: *"\(.*\)"/\1/')

  local abs_path
  abs_path="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
  local rel_path="${abs_path#${WORKSPACE_ROOT}/}"

  echo ""
  echo -e "${BOLD}=== 署名検証結果 ===${NC}"
  echo -e "  ファイル:     ${CYAN}${rel_path}${NC}"
  echo -e "  現在のハッシュ: ${current_hash:0:16}..."
  echo -e "  記録のハッシュ: ${recorded_hash:0:16}..."

  if [ "$current_hash" = "$recorded_hash" ]; then
    echo ""
    echo -e "  ${GREEN}${BOLD}[VALID] 署名は有効です - ドキュメントは署名後に変更されていません${NC}"
    echo ""

    # 署名者一覧を表示
    echo -e "  ${BOLD}署名者:${NC}"
    grep "name:" "$sig_file" | grep -v "filename:" | while read -r line; do
      local name
      name=$(echo "$line" | sed 's/.*: *"\(.*\)"/\1/')
      echo -e "    - ${name}"
    done
    echo ""
    return 0
  else
    echo ""
    echo -e "  ${RED}${BOLD}[INVALID] 署名は無効です - ドキュメントが署名後に変更されています${NC}"
    echo ""
    log_warning "ドキュメントの内容が署名時から変更されています。再署名が必要です。"
    return 1
  fi
}

# ================================================================
# サブコマンド: status
# ドキュメントの署名ステータスを表示する
# ================================================================
cmd_status() {
  local file="$1"

  if [ -z "$file" ]; then
    log_error "ファイルを指定してください"
    echo "使い方: $0 status <file>"
    exit 1
  fi

  if [ ! -f "$file" ]; then
    log_error "ファイルが見つかりません: $file"
    exit 1
  fi

  local sig_file
  sig_file="$(get_sig_file_path "$file")"

  if [ ! -f "$sig_file" ]; then
    echo ""
    echo -e "${YELLOW}このドキュメントは署名されていません${NC}"
    echo -e "署名するには: $0 sign $file"
    return 0
  fi

  local abs_path
  abs_path="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
  local rel_path="${abs_path#${WORKSPACE_ROOT}/}"
  local current_hash
  current_hash="$(compute_hash "$file")"
  local recorded_hash
  recorded_hash=$(grep "current_sha256:" "$sig_file" | head -1 | sed 's/.*: *"\(.*\)"/\1/')

  # 承認ステータスの取得
  local approval_status
  approval_status=$(grep "status:" "$sig_file" | tail -1 | sed 's/.*: *"\(.*\)"/\1/')

  echo ""
  echo -e "${BOLD}=== ドキュメント署名ステータス ===${NC}"
  echo -e "  ファイル:       ${CYAN}${rel_path}${NC}"
  echo -e "  ファイル名:     $(basename "$file")"

  # 整合性チェック
  if [ "$current_hash" = "$recorded_hash" ]; then
    echo -e "  整合性:         ${GREEN}[OK] 変更なし${NC}"
  else
    echo -e "  整合性:         ${RED}[NG] 署名後に変更あり${NC}"
  fi

  # 承認ステータス
  case "$approval_status" in
    approved)
      echo -e "  承認ステータス: ${GREEN}[承認済]${NC}"
      ;;
    pending)
      echo -e "  承認ステータス: ${YELLOW}[承認待ち]${NC}"
      ;;
    revoked)
      echo -e "  承認ステータス: ${RED}[取り消し]${NC}"
      ;;
    *)
      echo -e "  承認ステータス: ${YELLOW}[${approval_status}]${NC}"
      ;;
  esac

  # 署名者一覧
  echo ""
  echo -e "  ${BOLD}署名者一覧:${NC}"
  local sig_count=0
  grep "name:" "$sig_file" | grep -v "filename:" | while read -r line; do
    local name
    name=$(echo "$line" | sed 's/.*: *"\(.*\)"/\1/')
    echo -e "    - ${name}"
    sig_count=$((sig_count + 1))
  done

  # 署名日時
  local first_signed
  first_signed=$(grep "signed_first_at:" "$sig_file" | sed 's/.*: *"\(.*\)"/\1/')
  if [ -n "$first_signed" ]; then
    echo ""
    echo -e "  初回署名:       ${first_signed}"
  fi

  echo ""
}

# ================================================================
# サブコマンド: list
# 署名済みドキュメントの一覧を表示する
# ================================================================
cmd_list() {
  local search_dir="${1:-${WORKSPACE_ROOT}}"
  local sig_dir="${WORKSPACE_ROOT}/${SIGNATURES_DIR}"

  if [ ! -d "$sig_dir" ]; then
    log_info "署名されたドキュメントはありません"
    return 0
  fi

  local sig_files
  sig_files=$(find "$sig_dir" -name "*.sig.yaml" 2>/dev/null | sort)

  if [ -z "$sig_files" ]; then
    log_info "署名されたドキュメントはありません"
    return 0
  fi

  echo ""
  echo -e "${BOLD}=== 署名済みドキュメント一覧 ===${NC}"
  echo ""
  printf "  ${BOLD}%-50s %-12s %-20s${NC}\n" "ドキュメント" "ステータス" "署名者"
  echo "  $(printf '%.0s─' {1..82})"

  echo "$sig_files" | while read -r sig_file; do
    local doc_path
    doc_path=$(grep "path:" "$sig_file" | head -1 | sed 's/.*: *"\(.*\)"/\1/')
    local approval_status
    approval_status=$(grep "status:" "$sig_file" | tail -1 | sed 's/.*: *"\(.*\)"/\1/')

    # 署名者リストを取得
    local signers=""
    while read -r line; do
      local name
      name=$(echo "$line" | sed 's/.*: *"\(.*\)"/\1/')
      if [ -n "$signers" ]; then
        signers="${signers}, ${name}"
      else
        signers="${name}"
      fi
    done < <(grep "name:" "$sig_file" | grep -v "filename:")

    # ステータスの色付け
    local status_display
    case "$approval_status" in
      approved) status_display="${GREEN}承認済${NC}" ;;
      pending)  status_display="${YELLOW}承認待ち${NC}" ;;
      signed)   status_display="${BLUE}署名済${NC}" ;;
      revoked)  status_display="${RED}取り消し${NC}" ;;
      *)        status_display="${approval_status}" ;;
    esac

    # パスが長い場合は短縮
    local display_path="$doc_path"
    if [ ${#doc_path} -gt 48 ]; then
      display_path="...${doc_path: -45}"
    fi

    printf "  %-50s %-22b %-20s\n" "$display_path" "$status_display" "$signers"
  done

  echo ""
}

# ================================================================
# サブコマンド: approve
# ドキュメントを承認する
# ================================================================
cmd_approve() {
  local file=""
  local signer=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --signer) signer="$2"; shift 2 ;;
      *) file="$1"; shift ;;
    esac
  done

  if [ -z "$file" ]; then
    log_error "承認するファイルを指定してください"
    echo "使い方: $0 approve <file> [--signer <name>]"
    exit 1
  fi

  if [ ! -f "$file" ]; then
    log_error "ファイルが見つかりません: $file"
    exit 1
  fi

  local sig_file
  sig_file="$(get_sig_file_path "$file")"

  if [ ! -f "$sig_file" ]; then
    log_error "このドキュメントは署名されていません。先に署名してください。"
    echo "署名するには: $0 sign $file"
    exit 1
  fi

  signer="$(get_signer_name "$signer")"
  local timestamp
  timestamp="$(get_timestamp)"
  local current_hash
  current_hash="$(compute_hash "$file")"
  local recorded_hash
  recorded_hash=$(grep "current_sha256:" "$sig_file" | head -1 | sed 's/.*: *"\(.*\)"/\1/')

  # 整合性チェック
  if [ "$current_hash" != "$recorded_hash" ]; then
    log_error "ドキュメントが署名後に変更されています。再署名してから承認してください。"
    exit 1
  fi

  # 承認ステータスを更新
  sed -i "s/status: \"pending\"/status: \"approved\"/" "$sig_file"
  sed -i "s/approved_at: \"\"/approved_at: \"${timestamp}\"/" "$sig_file"

  local abs_path
  abs_path="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
  local rel_path="${abs_path#${WORKSPACE_ROOT}/}"

  append_sign_log "APPROVE" "$rel_path" "$signer" "$timestamp" "$current_hash"

  echo ""
  echo -e "${GREEN}${BOLD}=== 承認完了 ===${NC}"
  echo -e "  ファイル:   ${CYAN}${rel_path}${NC}"
  echo -e "  承認者:     ${BOLD}${signer}${NC}"
  echo -e "  日時:       ${timestamp}"
  echo ""
  log_success "ドキュメントが承認されました"
  echo ""
  echo -e "${BLUE}ヒント: 「確定反映して」コマンドでStockフォルダへの移動が推奨されます${NC}"
}

# ================================================================
# サブコマンド: revoke
# 署名を取り消す
# ================================================================
cmd_revoke() {
  local file=""
  local signer=""

  while [ $# -gt 0 ]; do
    case "$1" in
      --signer) signer="$2"; shift 2 ;;
      *) file="$1"; shift ;;
    esac
  done

  if [ -z "$file" ]; then
    log_error "ファイルを指定してください"
    echo "使い方: $0 revoke <file> [--signer <name>]"
    exit 1
  fi

  if [ ! -f "$file" ]; then
    log_error "ファイルが見つかりません: $file"
    exit 1
  fi

  local sig_file
  sig_file="$(get_sig_file_path "$file")"

  if [ ! -f "$sig_file" ]; then
    log_error "署名記録が見つかりません"
    exit 1
  fi

  signer="$(get_signer_name "$signer")"
  local timestamp
  timestamp="$(get_timestamp)"

  # ステータスを revoked に変更
  sed -i "s/status: \"approved\"/status: \"revoked\"/" "$sig_file"
  sed -i "s/status: \"pending\"/status: \"revoked\"/" "$sig_file"

  local abs_path
  abs_path="$(cd "$(dirname "$file")" && pwd)/$(basename "$file")"
  local rel_path="${abs_path#${WORKSPACE_ROOT}/}"

  append_sign_log "REVOKE" "$rel_path" "$signer" "$timestamp" ""

  echo ""
  echo -e "${RED}${BOLD}=== 署名取り消し ===${NC}"
  echo -e "  ファイル:   ${CYAN}${rel_path}${NC}"
  echo -e "  取消者:     ${BOLD}${signer}${NC}"
  echo -e "  日時:       ${timestamp}"
  echo ""
  log_warning "ドキュメントの署名が取り消されました"
}

# ================================================================
# サブコマンド: log
# 署名ログを表示する
# ================================================================
cmd_log() {
  local limit=20

  while [ $# -gt 0 ]; do
    case "$1" in
      --limit) limit="$2"; shift 2 ;;
      *) shift ;;
    esac
  done

  local log_file="${WORKSPACE_ROOT}/${SIGN_LOG_FILE}"

  if [ ! -f "$log_file" ]; then
    log_info "署名ログはまだありません"
    return 0
  fi

  echo ""
  echo -e "${BOLD}=== 署名ログ (最新${limit}件) ===${NC}"
  echo ""
  printf "  ${BOLD}%-22s %-10s %-15s %-40s${NC}\n" "日時" "操作" "署名者" "ファイル"
  echo "  $(printf '%.0s─' {1..87})"

  tail -n "$limit" "$log_file" | tac | while IFS='|' read -r timestamp action signer filepath hash; do
    # 前後の空白を除去
    timestamp=$(echo "$timestamp" | xargs)
    action=$(echo "$action" | xargs)
    signer=$(echo "$signer" | xargs)
    filepath=$(echo "$filepath" | xargs)

    # 操作の色付け
    local action_display
    case "$action" in
      SIGN)    action_display="${BLUE}署名${NC}" ;;
      APPROVE) action_display="${GREEN}承認${NC}" ;;
      REVOKE)  action_display="${RED}取消${NC}" ;;
      *)       action_display="$action" ;;
    esac

    # パスが長い場合は短縮
    local display_path="$filepath"
    if [ ${#filepath} -gt 38 ]; then
      display_path="...${filepath: -35}"
    fi

    printf "  %-22s %-20b %-15s %-40s\n" "$timestamp" "$action_display" "$signer" "$display_path"
  done

  echo ""
}

# ================================================================
# サブコマンド: help
# ヘルプメッセージを表示する
# ================================================================
cmd_help() {
  echo ""
  echo -e "${BOLD}Cloud Sign v${VERSION} - AIPM電子署名ツール${NC}"
  echo ""
  echo -e "${BOLD}使い方:${NC}"
  echo "  $0 <command> [options]"
  echo ""
  echo -e "${BOLD}コマンド:${NC}"
  echo -e "  ${CYAN}sign${NC}    <file> [--signer <name>]    ドキュメントに電子署名する"
  echo -e "  ${CYAN}verify${NC}  <file>                      署名の整合性を検証する"
  echo -e "  ${CYAN}status${NC}  <file>                      署名ステータスを表示する"
  echo -e "  ${CYAN}list${NC}    [directory]                  署名済みドキュメント一覧を表示する"
  echo -e "  ${CYAN}approve${NC} <file> [--signer <name>]    ドキュメントを承認する"
  echo -e "  ${CYAN}revoke${NC}  <file> [--signer <name>]    署名を取り消す"
  echo -e "  ${CYAN}log${NC}     [--limit <n>]               署名ログを表示する"
  echo -e "  ${CYAN}help${NC}                                このヘルプを表示する"
  echo ""
  echo -e "${BOLD}ワークフロー例:${NC}"
  echo "  1. ドラフト作成後、署名する:"
  echo "     $0 sign Flow/202602/2026-02-16/draft_project_charter.md"
  echo ""
  echo "  2. 署名を検証する:"
  echo "     $0 verify Flow/202602/2026-02-16/draft_project_charter.md"
  echo ""
  echo "  3. 承認する:"
  echo "     $0 approve Flow/202602/2026-02-16/draft_project_charter.md"
  echo ""
  echo "  4. 「確定反映して」でStockへ移動"
  echo ""
  echo -e "${BOLD}Flow→Stock 連携:${NC}"
  echo "  署名・承認済みドキュメントは「確定反映して」コマンドで"
  echo "  Stockフォルダへ移動できます。承認前の移動も可能ですが、"
  echo "  承認済みであることが推奨されます。"
  echo ""
}

# ================================================================
# メインルーティング
# ================================================================
main() {
  local command="${1:-help}"
  shift 2>/dev/null || true

  case "$command" in
    sign)    cmd_sign "$@" ;;
    verify)  cmd_verify "$@" ;;
    status)  cmd_status "$@" ;;
    list)    cmd_list "$@" ;;
    approve) cmd_approve "$@" ;;
    revoke)  cmd_revoke "$@" ;;
    log)     cmd_log "$@" ;;
    help|--help|-h) cmd_help ;;
    *)
      log_error "不明なコマンド: $command"
      cmd_help
      exit 1
      ;;
  esac
}

main "$@"
